apiVersion: v1
kind: Service
metadata:
  name: webgoat-service
  labels:
    app: webgoat        # ← ajoute cette ligne
spec:
  type: NodePort
  selector:
    app: webgoat
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      name: http        # ← ajoute cette ligne aussi
