apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: webgoat-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: webgoat
  endpoints:
    - port: http
      path: /WebGoat/actuator/prometheus
      interval: 30s
